#!/bin/bash

set -e
OUTPUT_FILE="$1"
VOLUME_NAME="$2"
shift;
shift;

rm -rf _dmg-build
mkdir _dmg-build

while [ x"$1" != x ]; do
    if [[ `basename "$1"` =~ ^dot ]]; then
        DEST=$(basename "$1" | sed -e 's/^dot-/./')
        echo "Copying $1 -> $DEST"
        rsync -aE "$1" "_dmg-build/$DEST"
    else
        echo "Copying $1"
        rsync -aE "$1" "_dmg-build"
    fi
    shift;
done

SetFile -a Vc _dmg-build/background.*
rm -f tmp.dmg
## For Creating the initial .DSStore:
# hdiutil create -size 200m -volname "Emacs" -fs HFS+J writable.dmg
rm -f "$OUTPUT_FILE"
# Strange work around for -5341 error on Mavericks:
# https://stackoverflow.com/questions/18621467/error-creating-disk-image-using-hdutil
# https://discussions.apple.com/thread/4712306
mkdir _dmg-build/.Trashes
dd if=/dev/zero of=_dmg-build/.Trashes/padding-because-hdiutil-sucks bs=1m count=2
hdiutil create -srcfolder _dmg-build -volname "$VOLUME_NAME" -format UDBZ "$OUTPUT_FILE"
