#!/bin/sh
set +e

if [[ ${*} == *help* ]]; then
    echo "Usage:"
    printf "\t$0 [bzr] [pretest] [release]\n"
    exit;
fi

for b in ${*:-bzr pretest release}; do
    b=${b##-}
    b=${b##--}
    eval build_$b=1
done

cd `dirname $0`
. ./notify
[ ${build_bzr}     ] && ./build-emacs-from-bzr && built=1
[ ${build_pretest} ] && ./build-emacs-from-ftp ftp://alpha.gnu.org/gnu/emacs/pretest pretest && built=1
[ ${build_release} ] && ./build-emacs-from-ftp ftp://ftp.gnu.org/gnu/emacs && built=1

-f build-emacs-post-hook && ./build-emacs-post-hook $built
