#!/bin/sh
set -e

. ./notify
. ./build-emacs-functions

REPO=bzr://bzr.savannah.gnu.org/emacs/trunk
BASE=Emacs-`date +%F`
CHANGES=emacs-builds/$BASE.changes

cd `dirname $0`
if [ ! -d emacs-bzr/trunk ]; then
    bzr init-repo emacs-bzr
    (cd emacs-bzr
	bzr checkout $REPO
    )
fi

(cd emacs-bzr/trunk
    OLDREV=`bzr revno`
    bzr pull $REPO
    NEWREV=`bzr revno`
    bzr log -p -r${OLDREV}..
)  | tee $CHANGES
DIR=emacs-bzr/build-`date +%F`
bzr checkout --lightweight --hardlink emacs-bzr/trunk "$DIR"

build_emacs "$DIR" $BASE
