#!/usr/bin/env ruby
#  Copyright © 2021 David Caldwell
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'optparse'

require_relative 'verbose-shell'
require_relative 'build-dependencies'

Vsh = VerboseShell

$all = false
(opts=OptionParser.new do |opts|
   me = File.basename($0)
   opts.banner = <<-USAGE
Usage:
    #{me} [-v]
    #{me} [-v] clean
    #{me} [-v] export-sources [--all] <dir>
  USAGE

   opts.on("-v", "--verbose", "Turn up the verbosity") { |v| Vsh.verbose = true }
   opts.on("-a", "--all", "Export build dependencies, too") { |a| $all = true }
   opts.on_tail("-h", "--help") { puts opts; exit }
end).parse!

build = BuildDependencies.new("dep")

if ARGV[0] == "clean"
  build.clean()
elsif ARGV[0] == "export-sources"
  build.export_sources(ARGV[1] || raise(opts.banner), $all)
else
  build.ensure()
end
