#!/usr/bin/env ruby

require 'json'
require_relative 'verbose-shell'

Vsh = VerboseShell
Vsh.verbose = true

abort "Usage: #{$0} dep_tar_files..." unless ARGV.count > 0

deps = ARGV.dup
base = File.basename(deps[0]).sub(/-[\d.]+-[^-]+-dependencies\.(json|tar)$/, '')

deps_dir = "#{base}-dependencies"
Vsh.rm_rf   deps_dir
Vsh.mkdir_p "#{deps_dir}/archives"

deps.each do |ar|
  os_arch=File.basename ar
  os_arch=os_arch.delete_prefix("#{base}-").delete_suffix("-dependencies.tar")
  Vsh.cd("#{deps_dir}/archives") { Vsh.system(*%W"tar xf ../../#{ar} --strip-components 1") }
  Vsh.capture(*%W"tar tf #{ar} *.tar.*").split.each do |f|
    puts f
    n=File.basename f
    Vsh.mkdir_p "#{deps_dir}/#{os_arch}"
    Vsh.ln_sf "../archives/#{n}", "#{deps_dir}/#{os_arch}/"
  end
end

Vsh.system(*%W"tar cf #{deps_dir}.tar #{deps_dir}")
Vsh.rm_rf deps_dir
