#!/bin/bash

set -e
set -x

base="${1?Usage: $0 base-name}"

deps="${base}-dependencies"
rm -rf  "$deps"
mkdir -p "$deps/archives"

for ar in label=*/*.tar; do
    (cd "$deps/archives" && tar xf ../../"$ar" --strip-components 1)
    for f in $(tar tf "$ar" "*.tar.*"); do
        echo "$f"
        n=$(basename "$f")
        d=$(basename "$ar")
        d=${d#"$base-"}
        d=${d%-dependencies.tar}
        mkdir -p "$deps/$d"
        ln -sf "../archives/$n" "$deps/$d/"
    done
done

tar cf "$deps.tar" "$deps"
rm -rf "$deps"
