#!/usr/bin/env ruby

require_relative 'verbose-shell'
Vsh = VerboseShell
Vsh.verbose = true

base = ARGV.shift or abort "Usage: #{$0} base-name"

deps = "#{base}-dependencies"
Vsh.rm_rf   deps
Vsh.mkdir_p "#{deps}/archives"

Dir["label=*/*.tar"].each do |ar|
  Vsh.cd("#{deps}/archives") { Vsh.system(*%W"tar xf ../../#{ar} --strip-components 1") }
  Vsh.capture(*%W"tar tf #{ar} *.tar.*").split.each do |f|
    puts f
    n=File.basename f
    d=File.basename ar
    d=d.delete_prefix("#{base}-").delete_suffix("-dependencies.tar")
    Vsh.mkdir_p "#{deps}/#{d}"
    Vsh.ln_sf "../archives/#{n}", "#{deps}/#{d}/"
  end
end

Vsh.system(*%W"tar cf #{deps}.tar #{deps}")
Vsh.rm_rf deps
