#!/usr/bin/env ruby
#  Copyright (c) 2016 David Caldwell
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'optparse'
require File.join ".",File.dirname(__FILE__),'verbose-shell.rb'
Vsh = VerboseShell

gitrev = nil

(opts=OptionParser.new do |opts|
  opts.banner = "Usage:\n\t#{$0} [options] <DIRECTORY> [<PACKAGE> ...]"
  opts.on("-v", "--verbose",                 "Turn up the verbosity")                          { |v|   Vsh.verbose = true }
  opts.on(      "--checkout=<GIT_REVISION>", "Checkout a particular git revision of homebrew") { |rev| gitrev = rev }
  opts.on_tail("-h", "--help") { puts opts; exit }
end).parse!

dir    = ARGV.shift || opts.abort("Missing <DIRECTORY>\n\n"+opts.help)

Vsh.system(*%W"git clone https://github.com/Homebrew/homebrew.git #{dir}") || abort("git failed!") unless File.exist?(dir)

Vsh.chdir(dir) || abort("chdir #{dir}: $!")

Vsh.system(*%W"git checkout #{gitrev}") || abort("git failed!") if gitrev

ENV['PATH'] = "#{Dir.pwd}/bin:#{ENV['PATH']}"

ARGV.each do |package|
  Vsh.systemr(*%W"brew upgrade #{package}") || Vsh.systemr(*%W"brew install #{package}") || abort("Couldn't install or upgrade")
end
