#!/usr/bin/env ruby
#  Copyright (c) 2016 David Caldwell
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'optparse'
require File.join File.expand_path(File.dirname(__FILE__)),'verbose-shell.rb'

def ensure_brew(dir, packages, options)
  vsh = VerboseShell
  vsh.verbose = options[:verbose]

  vsh.system(*%W"git clone https://github.com/Homebrew/homebrew.git #{dir}") || abort("git failed!") unless File.exist?(dir)

  vsh.chdir(dir) || abort("chdir #{dir}: $!")

  vsh.system(*%W"git checkout #{options[:gitrev]}") || abort("git failed!") if options[:gitrev]

  ENV['PATH'] = "#{Dir.pwd}/bin:#{ENV['PATH']}"

  packages.each do |package|
    vsh.systemr(*%W"brew upgrade #{package}") || vsh.systemr(*%W"brew install #{package}") || abort("Couldn't install or upgrade")
  end
end

if $0 == __FILE__
  gitrev = nil
  verbose = nil

  (opts=OptionParser.new do |opts|
     opts.banner = "Usage:\n\t#{$0} [options] <DIRECTORY> [<PACKAGE> ...]"
     opts.on("-v", "--verbose",                 "Turn up the verbosity")                          { |v|   verbose = true }
     opts.on(      "--checkout=<GIT_REVISION>", "Checkout a particular git revision of homebrew") { |rev| gitrev = rev }
     opts.on_tail("-h", "--help") { puts opts; exit }
   end).parse!

  dir    = ARGV.shift || opts.abort("Missing <DIRECTORY>\n\n"+opts.help)

  ensure_brew(dir, ARGV, :gitrev => gitrev, :verbose=>verbose)
end
