#!/usr/bin/env ruby
#  Copyright © 2014-2025 David Caldwell
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'json'
require 'optparse'
require_relative './ftp-versions'
require_relative './verbose-shell'
Vsh = VerboseShell

disable=""

(opts=OptionParser.new do |opts|
  opts.banner = "Usage:\n\t#{$0} [options] <meta-file>..."
  opts.on("-v", "--verbose", "Turn up the verbosity") { |v| Vsh.verbose = true }
  opts.on(      "--disable", "Touch disable-new-{kind} (for testing)") { disable = "disable-" }
  opts.on_tail("-h", "--help") { puts opts; exit }
end).parse!

metas = ARGV.dup.map { |f| JSON.parse(File.read(f)) }
opts.abort("Need at least one .meta file\n\n"+opts.help) if metas.length < 1

types = { pretest: { url: FtpVersions::PretestUrl,
                     meta: metas.find { |m| m['kind'] == 'pretest' } },
          release: { url: FtpVersions::ReleaseUrl,
                     meta: metas.find { |m| m['kind'] == 'release' } } }

types.each do |kind, config|
  puts "Checking for #{kind} in #{config[:url]}"
  latest = FtpVersions.versions(config[:url]).last

  warn "no current #{kind} found in .meta files" unless config[:meta]
  Vsh.touch("#{disable}new-#{kind}") unless latest[:version].to_s == config[:meta]&.send(:[], 'emacs_rev')
end
